create table if not exists public.meme_query_cache (
  id bigint generated by default as identity primary key,
  normalized text unique not null,
  original_query text not null,
  term jsonb not null,
  query_count integer not null default 1,
  provider text default 'deepseek',
  model text,
  created_at timestamptz not null default now(),
  last_queried_at timestamptz not null default now()
);

create table if not exists public.meme_candidates (
  id bigint generated by default as identity primary key,
  normalized text unique not null,
  original_query text not null,
  term text not null,
  category text default 'hot',
  query_count integer not null default 1,
  status text not null default 'collecting',
  updated_at timestamptz not null default now()
);

create table if not exists public.meme_query_logs (
  id bigint generated by default as identity primary key,
  term text not null,
  normalized text not null,
  hit boolean not null default false,
  source text not null,
  created_at timestamptz not null default now()
);

create index if not exists meme_query_logs_normalized_idx
  on public.meme_query_logs (normalized);

create index if not exists meme_query_logs_created_at_idx
  on public.meme_query_logs (created_at desc);

create table if not exists public.meme_trending_terms (
  id bigint generated by default as identity primary key,
  normalized text unique not null,
  term text not null,
  source text not null default 'weibo',
  source_url text,
  rank integer,
  heat text,
  reason text,
  category text default 'hot',
  tags jsonb not null default '[]'::jsonb,
  status text not null default 'candidate',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists meme_trending_terms_updated_at_idx
  on public.meme_trending_terms (updated_at desc);

create index if not exists meme_trending_terms_rank_idx
  on public.meme_trending_terms (rank);
